POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "New note 3",
  "author": "BS",
  "url": "www",
  "likes": "100"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJyeVNRIiwiaWQiOiI2NTgwZjFhZDJmNTgwZjU0M2Y1MmQyMzIiLCJpYXQiOjE3MDMwMTY3MTAsImV4cCI6MTcwMzAyMDMxMH0.Pn2He1h1pAubkhWEgIqwIB0E9O3VeGDfUr8FHW-vneg

{
  "title": "Authenticated blog number 3",
  "author": "BS",
  "url": "www",
  "likes": "100"
}

###
DELETE  http://localhost:3003/api/blogs/6580f7f1c47b3644c82f3aa8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJyeVNRIiwiaWQiOiI2NTgwZjFhZDJmNTgwZjU0M2Y1MmQyMzIiLCJpYXQiOjE3MDMwMTY3MTAsImV4cCI6MTcwMzAyMDMxMH0.Pn2He1h1pAubkhWEgIqwIB0E9O3VeGDfUr8FHW-vneg



###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "Josue Sandi",
  "username": "JosueSQ",
  "password": "bryanjaja"
}

###
#login
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "BrySQ",
  "password": "bryanjaja"
}